# file: {EIRC2 repo}./src/version.pri

VER_MAJOR = 5
VER_MINOR = 9
VER_RELEASE = 162
VER_BRANCH = 0
VER_STRING = "v5.09-Alpha2"
VER_TRUNKNAME = "develop"
VER_BRANCHNAME = ""
VER_QT = $${QT_VERSION}

windows:VERSION = 5.9.162.0
!windows:VERSION = 5.9.0
VER_MAJ = $${VER_MAJOR}
VER_MIN = $${VER_MINOR}
VER_PAT = $${VER_BRANCH}

#message("Version = $${VER_STRING}+$${EIRC_VER_BRANCHNAME} $${VER_TRUNKNAME}")
#message("QMAKESPEC = $${QMAKESPEC}")
